# -- Theme Options --
colorScheme = "teal"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true
enableA11y = true

mainSections = ["articles"]
robots = "index, follow"

disableImageOptimization = false
disableTextInHeader = false

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "custom"
  showRecent = false
  showRecentItems = 0
  showMoreLink = false
  cardView = false

[article]
  showDate = true
  showDateUpdated = false
  showViews = false
  showLikes = false
  showAuthor = true
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  showTaxonomies = true
  showWordCount = false
  sharingLinks = []
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]
